// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace atendimentoEmpresaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231031023044_initialData")]
    partial class initialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Cep")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("PessoaFisicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaID")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("EnderecoID");

                    b.HasIndex("PessoaFisicaID");

                    b.HasIndex("PessoaJuridicaID");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Models.PessoaFisica", b =>
                {
                    b.Property<int>("PessoaFisicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Cpf")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Idade")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("PessoaTipo")
                        .HasColumnType("int");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("Telefone")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("PessoaFisicaID");

                    b.ToTable("PessoasFisicas");
                });

            modelBuilder.Entity("Models.PessoaJuridica", b =>
                {
                    b.Property<int>("PessoaJuridicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Cnpj")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("PessoaTipo")
                        .HasColumnType("int");

                    b.Property<int?>("Telefone")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("PessoaJuridicaID");

                    b.ToTable("PessoasJuridicas");
                });

            modelBuilder.Entity("Protocolo", b =>
                {
                    b.Property<int>("ProtocoloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PessoaFisicaID")
                        .HasColumnType("int");

                    b.Property<int>("PessoaJuridicaID")
                        .HasColumnType("int");

                    b.HasKey("ProtocoloID");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("Models.Endereco", b =>
                {
                    b.HasOne("Models.PessoaFisica", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaFisicaID");

                    b.HasOne("Models.PessoaJuridica", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaJuridicaID");
                });

            modelBuilder.Entity("Models.PessoaFisica", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("Models.PessoaJuridica", b =>
                {
                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
